### ISSUE TITLE
"duplicate symbols for architecture..." errors on build

### ISSUE THREAD

**Issue by thisisaaronland** [psanford/sqlite3vfs#1]
Hi,

First, thanks for writing this. It's crossed my mind to try and do something similar for a variety of projects but I haven't been able to find the time. 

I am seeing the following errors when I try to build (or test) this package (or `sqlite3vfshttp`). Perhaps I am just missing something obvious?

```
$> go version
go version go1.16.7 darwin/amd64

$> go build ./...
# github.com/psanford/sqlite3vfs
duplicate symbol '_s3vfs_io_methods' in:
    $WORK/b001/_x001.o
    $WORK/b001/_x002.o
duplicate symbol '_s3vfs_io_methods' in:
    $WORK/b001/_x001.o
    $WORK/b001/_x003.o
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by psanford** [comment]
I have a few ideas what might be the problem.

`go-sqlite3` vendors all of the sqlite c code into its repo. That makes it easy to build and include in other go projects.

Ideally, sqlite3vfs would simply reference and link to that copy of the sqlite c code. Unfortunately, so far I've not been able to figure out how to get the Go compiler to allow you to do this.

Currently `sqlite3vfs` uses the system installed `sqlite3` package to link against. That has worked on the machine I've been developing on, but it isn't too surprising that it doesn't work in all environments.

I'll spend some more time trying to get a build working without depending on a system installed `sqlite3` library.

I also haven't tried building this on macOS yet, so let me try that and see if I can reproduce the error you are seeing.

**Comment by psanford** [comment]
I was able to reproduce the build issue on a macOS host. The fix ended up not being related to how we are linking sqlite3, but just a duplicate local definition. 

If you are still having this issue after upgrading, please re-open this issue. Thanks!

**Comment by thisisaaronland** [comment]
Works for me. Thanks!

```
$> go test -v ./...
=== RUN   TestSqlite3vfs
--- PASS: TestSqlite3vfs (0.04s)
PASS
ok  	github.com/psanford/sqlite3vfs	0.229s
```
