### ISSUE TITLE
zstd extension for read only

### ISSUE THREAD

**Issue by jtarchie** [psanford/sqlite3vfs#13]
First, thanks for creating this. It made it easy to create the second thing.

Second, I created a read-only [zstd extension](https://github.com/jtarchie/sqlitezstd). The `README` will explain more, but the TLDR is: Compress your SQLite database with zstd seekable for read-only access.

Third, is a PR for adding it to your README acceptable?

**Comment by psanford** [comment]
Neat! 

I'd take a PR for the README :+1:

**Comment by jtarchie** [comment]
Done #14
